blank_issues_enabled: false
contact_links:
  - name: â“ Discussion
    url: https://github.com/Alef-Burzmali/netbox-data-flows/discussions
    about: "If you're just looking for help, try starting a discussion instead."
  - name: ğŸš¨ Security issues
    url: https://github.com/Alef-Burzmali/netbox-data-flows/security
    about: "Use the Security Advisories to report security issues. You will be credited."
